name: All Branches
on: push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install Arduino tools
        run: |
          pip install cpplint
      - name: Install webapp tools
        run: |
          yarn add eslint
          yarn add stylelint
      - name: Run ESLint checks
        run: |
          yarn run eslint ./webapp/*.js
      - name: Run StyleLint checks
        run: |
          yarn run stylelint ./webapp/*.css
      - name: Run C++ linter
        run: |
          cpplint --extensions=ino **/*.ino
      - name: Validate Swagger docs
        uses: mbowman100/swagger-validator-action@master
        with:
          files: |
            openapi-spec.yaml
      - name: Cleanup
        run: |
          rm -rf node_modules
          rm package.json
          rm yarn.lock

  test-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout custom WiFi library
        uses: actions/checkout@v2
        with:
          repository: skhg/home_wifi
          ref: master
          path: CustomHomeWiFiLibrary # must contain string "Custom"
      - name: Checkout custom Async TCP library
        uses: actions/checkout@v2
        with:
          repository: me-no-dev/ESPAsyncTCP
          ref: master
          path: CustomAsyncTCPLibrary # must contain string "Custom"
      - name: Test compile for Arduino
        uses: ArminJo/arduino-test-compile@v3
        with:
          arduino-board-fqbn: esp8266:esp8266:nodemcu:xtal=80,vt=flash,exception=legacy,ssl=all,eesz=4M2M,ip=lm2f,dbg=Disabled,lvl=None____,wipe=none,baud=115200
          platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
          required-libraries: DHT sensor library,ArduinoJson,WebSockets
          sketch-names: "*.ino"
